name: Publish PowerShell Module

on:
  push:
    branches:
      - main

jobs:
  publish-to-gallery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install InvokeBuild
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module InvokeBuild -ErrorAction Stop
      - name: Build and publish
        env:
          NUGET_KEY: ${{ secrets.NUGET_KEY }}
        shell: pwsh
        run: |
          Invoke-Build -Task Build -Configuration Release -Sourcelocation {{ env.GITHUB_SERVER_URL}}{{ env.GITHUB_REPOSITORY }}
          Publish-Module -Path /build/CogniteInsoModule -NuGetApiKey $env:NUGET_KEY -Verbose